dbslower: Fixes build errors caused by uninitialized variables in bpf program
In a lower version of clang (such as Clang-10), if the variable is not
initialized in the bpf program, the symbol will not know which section
to store, and the build will fail.

$ make
  GEN-SKEL ugc.skel.h
libbpf: sec '.relusdt': corrupted symbol #43 pointing to invalid section #65522 for relo #5
Error: failed to open BPF object file: BPF object format invalid

Signed-off-by: Youling Tang <tangyouling@kylinos.cn>
Change-Id: Ibb612cedbb3da5ed3a324ad748b5b8851cfa529d
Reviewed-on: http://gerrit.kylin.com/c/ketones/+/77476
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>